#! /usr/bin/env python

import os
import sys
import optparse

from pycparser import parse_file, c_ast, c_generator, plyparser

########################################################################################################################

def fatal(msg):    
    sys.stderr.write(str(msg) + "\n")
    sys.exit(-1)
            
########################################################################################################################

class CModule(object):
    """represents a C module that can be parsed"""

    @staticmethod
    def parse(filename, cpp_args=None):
        """parses file and return a CModule"""
        content = open(filename, "r").read()
        try:
            node    = parse_file(filename, use_cpp=True, cpp_args=cpp_args)
        except plyparser.ParseError as e:
            fatal(e)
        return CModule(node, filename, content)

    def __init__(self, node, filename, content):
        """builds a new CModule object"""
        self.node     = node
        self.filename = filename
        self.content  = content
            
    def get_name(self):
        """returns the name of the module, i.e. the file name without extension"""
        _, module = os.path.split(self.filename)
        if (module.endswith(".c")): module = module.replace(".c","")
        if (module.endswith(".C")): module = module.replace(".C","")
        return module;
    
    def get_filename(self):
        """returns the absolute filename of the module""" 
        return os.path.abspath(self.filename)
    
    def get_lines(self):
        """returns a list containing the lines of the original module (before preprocessing)"""
        return self.content.splitlines()
            
    
    def get_function_definitions(self):
        """returns the list of function definitions as a list of FunctionDefinition"""
        result = []
        
        class Visitor(c_ast.NodeVisitor):
            def visit_FuncDef(self, node):
                result.append(FunctionDefinition.parse(node))
                
        Visitor().visit(self.node)
                    
        return result
    
    def get_double_definitions(self):
        """returns the list of double definitions as a list of DoubleDefinition"""
        result = []
        
        class Visitor(c_ast.NodeVisitor):
            def visit_FuncDef(self, node):
                double_def = DoubleDefinition.parse(node)
                if (double_def): result.append(double_def)
                
        Visitor().visit(self.node)
                    
        return result
        
    
########################################################################################################################
    
class FunctionDefinition(object):
    """represents a function definition inside a C module"""
    
    @staticmethod
    def parse(node):
        """parses a FuncDef node and returns a FunctionDefinition"""
        rtype = FunctionDefinition.parse_rtype(node)        
        args  = FunctionDefinition.parse_args(node)
        body  = FunctionDefinition.body_contains_double_definition(node)
        return FunctionDefinition(node, rtype, args, body)
    
    @staticmethod
    def parse_args(node):
        """parses the formal argument of the function and stores them in object"""
        args = dict(node.decl.type.children()).get('args', None)
        if not args: return []
            
        result = []
        for _, arg_declaration in args.children():
            if 'type' in dict(arg_declaration.children()):
                result.append(FormalArgument.parse(arg_declaration))
        return result
    
    @staticmethod
    def body_contains_double_definition(node):
        """parses the body of the function and returns it as a list of AST nodes"""
        body_node = dict(node.children()).get("body", None)
        if not body_node: return []
        return [ instruction for _, instruction in body_node.children() ]

    @staticmethod
    def parse_rtype(node):
        """parses the return type of the function and returns it as a string"""
        generator = c_generator.CGenerator()
        type_node = dict(dict(node.decl.children())['type'].children())['type']
        return_type_and_function_name = generator._generate_type(type_node)
        return return_type_and_function_name[:-len(node.decl.name)].strip()

    def __init__(self, node, rtype, args, body):
        """builds a new FunctionDefinition object"""
        self.node     = node
        self.rtype    = rtype
        self.args     = args
        self.body     = body
        self.args_map = dict( (arg.get_name(), arg) for arg in self.args)
             
    def get_name(self):
        """returns the name of the function being defined"""
        return self.node.decl.name

    def get_rtype(self):
        """returns the return type of the function as a string"""
        return self.rtype
    
    def get_formal_arguments(self):   
        """returns the list of formal arguments of the function as a list of FormalArgument"""     
        return self.args

    def get_formal_argument(self, name):
        """returns the argument corresponding to provided argument name as a FormalArgument"""
        return self.args_map.get(name, None)

    def get_body(self):
        """returns the body of the function as a list of AST nodes"""
        return self.body
    
    def get_declaration_line(self):
        """returns the list at which the function declaration is done withing its module"""
        return self.node.decl.coord.line-1
    
    def get_body_lines(self):
        """returns a range of line number in the module of the body of the function""" 
        return range(self.body[0].coord.line-1, self.body[-1].coord.line)
    
########################################################################################################################

class FunctionCall(object):
    """represents a function call instructions"""
    
    @staticmethod
    def parse(node):
        """parses a FuncCall node and returns a FunctionCall"""
        args = FunctionCall.parse_args(node)
        return FunctionCall(node, args)
    
    @staticmethod
    def parse_args(node):
        """parses the actual argument of the function call  and returns it as a list of string"""    
        expr_list = dict(node.children()).get("args", None)
        if expr_list:
            generator = c_generator.CGenerator()
            return [ generator.visit(expr) for _, expr in expr_list.children() ]
        else:
            return []

    def __init__(self, node, args):
        """builds a new FunctionCall object"""
        self.node = node;
        self.args = args
        
    def get_called(self):
        """returns the function called as a string"""
        return self.node.name.name
    
    def get_args(self):
        """returns the list of actual arguments as a list of string"""
        return self.args
        
    def get_arg(self, n):
        """returns the n^th actual argument of a function call"""
        return self.get_args()[n]
            

########################################################################################################################

class FormalArgument(object):
    """represents a formal argument in the a function definition"""
    
    @staticmethod
    def parse(node):
        """parses a TypeDecl node (assumed to ba a formal argument) and returns a FormalArgument"""
        return FormalArgument(node)

    def __init__(self, node, tag=None):
        """builds a new FormalArgument object"""
        self.node        = node
        self.tag         = tag
    
    def has_pointer_type(self):
        """returns True is the type of the argument is a pointer type"""
        return isinstance(self.get_type_node(), c_ast.PtrDecl)

        return True
    
    def get_type_node(self):
        """returns the type node of the argument"""
        return dict(self.node.children())['type']
    
    def get_name(self):
        """returns the name of the argument as a string"""
        return self.node.name
    
    def get_declaration(self):
        """returns the declaration of the argument as a string"""
        generator = c_generator.CGenerator()
        return generator._generate_type(self.get_type_node())

    def get_type(self):
        """returns the type of the argument... well mostly does not work for [] types"""
        return self.get_declaration().replace(self.get_name(),"").strip()
           
    def get_dereferenced_declaration(self):
        """return a declaration of the argument with one less pointer indirection, e.g. 'int *p' --> 'int p'"""
        generator = c_generator.CGenerator()
        deref_type_node = dict(self.get_type_node().children())['type']
        return generator._generate_type(deref_type_node)

    def get_dereferenced_type(self):
        """returns the dereferenced type of the argument... well mostly does not work for [] types"""
        return self.get_dereferenced_declaration().replace(self.get_name(),"")
                  
    def set_tag(self, tag):
        """allows to set_tag the argument"""
        self.tag = tag
        
    def get_tag(self):
        """allows to retrieve the tag"""
        return self.tag 

########################################################################################################################

class DoubleDefinition(FunctionDefinition):
    """
    represents a double definition i.e. a classical function definition whose body is only composed of 
    macro call to INPUT_VALUE, INPUT_STRING, INPUT_MEMORY, OUTPUT_VALUE, or RETURN. Functions with empty
    body are not considered
    """
       
    @staticmethod
    def parse(node):
        """parses a FuncDef node, returns a DoubleDefinition if the FuncDef contains only macro call, None otherwise"""               
        func_def = FunctionDefinition.parse(node)
        if DoubleDefinition.body_contains_double_definition(func_def):
            double_def = DoubleDefinition(node, func_def.rtype, func_def.args, func_def.body)
            DoubleDefinition.tag_arguments_with_macro_calls(double_def)
            DoubleDefinition.check_output_arguments(double_def) 
            return double_def
        return None
        
    @staticmethod
    def body_contains_double_definition(func_def):
        """returns true is the function definition contains only a non-empty list of double macro calls"""
        found_double_macros     = False
        found_other_instruction = False
        
        for instruction in func_def.get_body():
            if DoubleDefinition.parse_one_macro_call(func_def, instruction): 
                found_double_macros = True
            else:
                found_other_instruction = True
                
            if found_double_macros and found_other_instruction:
                fatal(str(instruction.coord) + ": cannot mix double definition instructions with other instructions")
                
        return found_double_macros
        
        
    @staticmethod
    def parse_one_macro_call(func_def, instruction):
        """parses an instruction ast node and returns a Function"""
        if not isinstance(instruction, c_ast.FuncCall): 
            return None
        
        call = FunctionCall.parse(instruction)
        
        expected_n_arg = {
            "INPUT_VALUE"  : 1, 
            "INPUT_MEMORY" : 2,
            "INPUT_STRING" : 1,
            "OUTPUT_VALUE" : 2,
            "RETURN"       : 0 if func_def.get_rtype() == "void" else 1,  
        }

        if call.get_called() not in expected_n_arg:
            return None
        if len(call.get_args()) < expected_n_arg[call.get_called()]:            
            fatal(str(instruction.coord) + ": missing argument in call to '%s'" % call.get_called())
        if len(call.get_args()) > expected_n_arg[call.get_called()]:
            fatal(str(instruction.coord) + ": too many argument in call to '%s'" % call.get_called())
            
        return call
        
    @staticmethod
    def tag_arguments_with_macro_calls(double_def):
        """tags each formal argument with the macro call within the double definition body linked to that argument"""
        calls = double_def.get_macro_calls("INPUT_") + double_def.get_macro_calls("OUTPUT_")        
        for call in calls:
            arg_name   = call.get_arg(0)
            formal_arg = double_def.get_formal_argument(arg_name)
            if not formal_arg:
                fatal(str(call.node.coord) +
                      ": '%s' is not a formal argument of '%s' in call to '%s'" %
                      (arg_name, double_def.get_name(), call.get_called()) 
                )
            formal_arg.set_tag(call)
           
    @staticmethod
    def check_output_arguments(double_def):
        """check if output arguments are indeed pointer types"""
        for call in double_def.get_macro_calls("OUTPUT_"):
            arg_name   = call.get_arg(0)
            formal_arg = double_def.get_formal_argument(arg_name)
            if not formal_arg.has_pointer_type():
                fatal(str(call.node.coord) + 
                      ": '%s' has a non-pointer type '%s' which cannot be used as output argument for '%s'" %
                      (arg_name, formal_arg.get_type(), double_def.get_name())
                )
        pass
           

    def get_macro_calls(self, macro_prefix):
        """returns the list of macro calls matching a given prefix as a list of FunctionCall"""
        result = []
        for instruction in self.get_body():
            call = FunctionCall.parse(instruction)
            if call.get_called().startswith(macro_prefix):
                result.append(call)
        return result

    def get_return_statement(self):
        """returns the RETURN statement of the double definition as a FunctionCall"""
        return self.get_macro_calls("RETURN")[0]
                            
    def get_default_return_value(self):
        """returns the default return value of the double, i.e. the first argument of the RETURN macro call"""
        args = self.get_return_statement().get_args()
        return args[0] if args else "NULL"
            
    def get_mock_formal_argument_declarations(self):
        """return the formal arguments declaration of the MOCK_foo function as a comma seperated string"""        
        return ", ".join(arg.get_declaration() for arg in self.get_formal_arguments() if not arg.get_tag().get_called().startswith("OUTPUT_"))
        
    def get_stub_default_actual_arguments(self):
        """returns the default stub argument as one comma separated string"""
        expression_list = []
        
        if self.get_return_statement().get_args():
            expression_list.append(self.get_return_statement().get_arg(0))

        for arg in self.get_formal_arguments():
            if arg.get_tag().get_called() == "OUTPUT_VALUE":
                expression_list.append(arg.get_tag().get_arg(1))
                        
        return ", ".join(expression_list)
    
    def get_stub_formal_argument_declarations(self):
        """returns the formal arguments of the STUB_foo function as a comma seperated string"""
        declaration_list = []
    
        if self.get_rtype() != "void":
            declaration_list.append(self.get_rtype() + " return_value");

        for arg in self.get_formal_arguments():
            if arg.get_tag().get_called() == "OUTPUT_VALUE":
                declaration_list.append(arg.get_dereferenced_declaration())
            
        return ", ".join(declaration_list)
    
########################################################################################################################

class MockGenerator(object):
    
    def __init__(self, module, output):
        """builds a MockGenerator object"""
        self.module = module
        self.output = output        

    def writeln(self, text=""):
        """writes some text followed by a new line to the output"""
        self.output.write(text + "\n")

    def generate_stub(self, double_def):
        """generates the STUB_foo() function"""
        return_type      = double_def.get_rtype()
        function_name    = double_def.get_name()
        formal_arguments = double_def.get_stub_formal_argument_declarations()
        return_value     = "return_value" if return_type != "void" else "NULL"
                
        self.writeln("")
        self.writeln("void STUB_{function_name}({formal_arguments})".format(**locals()))
        self.writeln("{")
        for call in double_def.get_macro_calls("INPUT_"):
            if call.get_called() in [ "INPUT_VALUE", "INPUT_STRING" ]:
                (name,) = call.get_args()
                self.writeln("    expect_any({function_name}, {name});".format(**locals()))
            elif call.get_called() == "INPUT_MEMORY":
                (name,size) = call.get_args()
                self.writeln("    expect_any({function_name}, {name});".format(**locals()))
        for call in double_def.get_macro_calls("OUTPUT_"):
            if call.get_called() == "OUTPUT_VALUE":
                (name,_) = call.get_args()
                self.writeln("    expect_not_value({function_name}, {name}, NULL);".format(**locals()))
                self.writeln("    will_return({function_name}, {name});".format(**locals()))                            
        self.writeln("    will_return({function_name}, {return_value});".format(**locals()))
        self.writeln("}")
        self.writeln()        

    def generate_mock(self, double_def):
        """generates the MOCK_foo() function"""
        function_name        = double_def.get_name()
        formal_arguments     = double_def.get_mock_formal_argument_declarations()
        default_return_value = double_def.get_default_return_value()
        
        self.writeln("void MOCK_{function_name}({formal_arguments})".format(**locals()))
        self.writeln("{")
        for call in double_def.get_macro_calls("INPUT_"):
            if call.get_called() == "INPUT_VALUE":
                (name,) = call.get_args()
                self.writeln("    expect_value({function_name}, {name}, {name});".format(**locals()))
            elif call.get_called() == "INPUT_STRING":
                (name,) = call.get_args()
                self.writeln("    expect_string({function_name}, {name}, {name});".format(**locals()))
            elif call.get_called() == "INPUT_MEMORY":
                (name, size) = call.get_args()
                self.writeln("    expect_memory({function_name}, {name}, {name}, {size});".format(**locals()))
        for call in double_def.get_macro_calls("OUTPUT_"):
            if call.get_called() == "OUTPUT_VALUE":
                (name, default) = call.get_args()
                self.writeln("    expect_not_value({function_name}, {name}, NULL);".format(**locals()))
                self.writeln("    will_return({function_name}, {default});".format(**locals()))
        self.writeln("    will_return({function_name}, {default_return_value});".format(**locals()))                
        self.writeln("}")    
        self.writeln()    
        
    def generate_double_body(self, double_def):
        """generates the body of the foo() function"""
        function_name        = double_def.get_name()
        return_type          = double_def.get_rtype()
        default_stub_args    = double_def.get_stub_default_actual_arguments()   
        return_or_not_return = "return " if return_type != "void" else ""
        
        self.writeln("    if (auto_stub())")
        self.writeln("        STUB_{function_name}({default_stub_args});".format(**locals()))
        for call in double_def.get_macro_calls("INPUT_"):
            if call.get_called() in [ "INPUT_VALUE", "INPUT_STRING" ]:
                (name,) = call.get_args()
                self.writeln("    check_expected({name});".format(**locals()))
            elif call.get_called() == "INPUT_MEMORY":
                (name, size) = call.get_args()
                self.writeln("    check_expected({name});".format(**locals()))
        for call in double_def.get_macro_calls("OUTPUT_"):
            if call.get_called() == "OUTPUT_VALUE":
                (name,_) = call.get_args()
                type = double_def.get_formal_argument(name).get_dereferenced_type()
                self.writeln("    check_expected({name});".format(**locals()))
                self.writeln("    *({name}) = ({type})mock();".format(**locals()))
        self.writeln("    {return_or_not_return}({return_type})mock();".format(**locals()))

    def build_line_map(self):
        """returns a map giving for each line number the DoubleDefinition occurring at this line if applicable"""  
        line_map = {}        
        for double_def in self.module.get_double_definitions():
            for i in double_def.get_body_lines():
                line_map[i] = double_def
            line_map[double_def.get_declaration_line()] = double_def
        return line_map

    def generate(self):
        """
        This is where all the magic happens. The un-pre-processed module is transformed as follows:
            - before any double definition foo(), two additional function MOCK_foo() and STUB_foo() are added
              with appropriate cmockery code (expect_any, expect_value, expect_stirng, expect_memory, ...)
            - the body of the double function is replaced with correct cmockery code (check_expected(), mock(), ...)
            - all other lines are copied through untouched
        """
        lineno   = 0
        lines    = self.module.get_lines()
        line_map = self.build_line_map()

        while lineno < len(lines):
            double = line_map.get(lineno, None)
            if not double:
                self.writeln(lines[lineno])
            elif lineno == double.get_declaration_line():
                self.generate_stub(double)
                self.generate_mock(double)
                self.writeln(lines[lineno])
            elif lineno in double.get_body_lines():
                self.generate_double_body(double)
                lineno = double.get_body_lines()[-1]
            lineno += 1
           
########################################################################################################################
    
def parse_args():
    """parses the command line argument, see 'mockme --help' for details"""
    parser = optparse.OptionParser(
        usage="%prog [options] <INFILE>", 
        description="Automatically generates and add cmockery mocks/stubs/double functions to a C module.",
        epilog="/!\ do not forget the -I/path/to/fake_libc" 
    )

    parser.add_option("-I", action="append", default=[], dest="includes", metavar="<DIR>", 
                      help="add the directory <DIR> to the list of directories to be searched for header files.")
    parser.add_option("-D", action="append", default=[], dest="defines", metavar="<NAME>", 
                      help="predefine <NAME> as a macro, with definition 1")
    parser.add_option("-o", action="store", default=None, dest="output", metavar="<OUTFILE>",
                      help="sets <OUTFILE> as output; if no file is provided, the standard output will be used")
    args, remaining = parser.parse_args()
        
    if len(remaining) != 1: 
        parser.print_help()
        sys.exit(-1)
        
    args.input  = remaining[0]
    args.output = open(args.output, "w") if args.output else sys.stdout
    args.cpp_args = [ 
        r"-nostdinc",
        r"-DMOCK_ME",
        r"-DUNDER_TEST" 
    ]

    for dir in args.includes:
        args.cpp_args.append(r"-I" + dir)
    for name in args.defines:
        args.cpp_args.append(r"-D" + name)
    
    return args
    
########################################################################################################################
    
if __name__=="__main__":
    args = parse_args()
    MockGenerator(CModule.parse(args.input, args.cpp_args), args.output).generate()

