Import("root")

demo = root.Clone()
demo.MergeFlags("-I#include")
demo.Program("demo", Split("demo.c"))

test = root.Clone(OBJSUFFIX=".test.o")
test.MergeFlags("-I#include")
test.MergeFlags("-DUNDER_TEST")
test.MergeFlags("-lmockme -L#mockme")
test.MockMe("demo_unit_test_mocked.c", "demo_unit_test.c")
test.UnitTest("demo_unit_test", Split("demo.c demo_unit_test_mocked.c"))